CREATE VIEW ORDERS AS 
    SELECT a.SNAME, SUM(b.AMT)
        FROM SAL a, ORD b
        WHERE a.SNUM = b.SNUM
        GROUP BY a.SNAME;
     
CREATE ROLE BATYA;
GRANT SELECT, UPDATE ON CUST TO BATYA;	 
		
GRANT SELECT 
    ON BR33.ORDERS 
    TO PUBLIC;

GRANT SELECT
    ON CUST, ORD
    TO UP2;

GRANT BATYA TO UP1, UP2;

REVOKE UPDATE ON CUST33 FROM BATYA;